### ISSUE TITLE
Documentation style

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#44]
What is the policy on documentation style?

Right now we have some `.lhs` files written in a bird-tack markdown style and some `.hs` files with markdown in block comments.

Are you using pandoc to process the markdown into something? If so, can you share a script for invoking it as you do so that contributors can be sure not to break it?

It's presumably desirable to have haddock comments as well. Or is it? If so, how do we make those coexist with the literate markdown? I tried researching this and found [this StackOverflow question](http://stackoverflow.com/questions/2707645/literate-haskell-lhs-and-haddock). The answers are informative and interesting, but AFAICT don't actually answer the most direct part of the question, which I would phrase as "what is the example syntax of a haddock commented declaration that will be acceptable to both haddock and the literate markdown processor?".

**Comment by dmcclean** [comment]
See https://github.com/bjornbm/dimensional-dk/commit/fcd7245aba169c6064e9457d2515b251cb1f6678 for an example of how I plan to do this. Easier to make changes after just having done one, before I go and do the others.

I recommend pulling it and `cabal haddock`ing it to see how it looks, since I don't have a convenient place to host the result.

(Don't be scared off by the first 3 lines of the diff, they were redundant with other ones further down in the haddock module header.)

**Comment by bjornbm** [comment]
I like it, thanks for doing this! Once the modules are converted we should proof read (I promise I can help with that!). For example I think e.g. the disclaimer can be removed. And unless you object I think we should also add you as a maintainer. ;)

**Comment by dmcclean** [comment]
I phrased this as a pull request to ease review of the diffs.

If you want to make changes, I'm not sure if there's an easy way to accept the pull request as a new branch to this repository (as opposed to directly merging it with master). If there isn't and so you want commit rights in my fork or for me to make specific tweaks, let me know.

In a few places I removed some of the hesitant language, especially where the relevant issues had since been resolved by other efforts. I made up a few things from whole cloth where it seemed appropriate.

More could obviously be done in terms of explaining the nuances behind various bizarre units, which the Fortress prelude had done a great job of, but I can't seem to find a live link to it. I don't feel that that's in scope of this issue because it is a lot of work with an indefinite end point.

I have no objection to be added as a maintainer.

**Comment by dmcclean** [comment]
Oh, and I also normalized tabs to spaces in a few places, since the default GHC 7.10 settings are to issue a warning about every tab character in the file!

**Comment by dmcclean** [comment]
See https://github.com/isaacs/github/issues/18 if you are curious. Apparently a lot of people had the same wish, for an easy way to merge a pull request to a new branch, but it doesn't exist yet. From the CLI you can do it, though.

**Comment by dmcclean** [comment]
Resolved by #55.
