### ISSUE TITLE
Are negative units allowed?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#49]
Is there any sense to allowing negative units, e.g. definitions of the following form:

````
negawatt :: Unit DEnergy
negawatt = prefix (-1) (mega watt)
````

I don't believe there is. I am contemplating a change that would make it less fully supported, and I'm wondering if perhaps it should be banned outright as unexpected and a potential trap.

AFAICS, the NIST Guide doesn't have anything to say about this. The UCUM disallows it, see http://unitsofmeasure.org/ucum.html#section-Syntax-Rules.

**Comment by dmcclean** [comment]
To be clear, this is fully supported right now with no problems that I can see. It does exactly what you would expect it to do, provided you would expect it to do something.

**Comment by bjornbm** [comment]
As far as I am concerned dropping support for negative units is not a problem, so don't let them hold you back!

As for banning them outright I don't know if I feel it is necessary, unless they are otherwise less fully supported (e.g. by your contemplated change).

**Comment by dmcclean** [comment]
Came back to look at this after realizing (in another thread) that, while negative units are merely head-scratching, zero units are pretty awful.

It turns out we can't really ban them, because we don't have enough context in `prefix :: Num a => a -> Unit d a -> Unit d a` to discriminate based on the sign of the supplied coefficient.

Adding an `Eq` context (which would be enough for either purpose, because `signum` is in `Num`) isn't desirable because we'd lose the ability to operate with certain useful abstract number types.

Going to add a stern warning against using zero to the documentation, and a note that using negative values may be unexpected by others.
