### ISSUE TITLE
Documentation style

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#51]
Right now a couple of the files are literate haskell with markdown (I think?) comments in the bulk of the files. The others are ordinary haskell files with markdown (again, I think) comments.

One drawback to this state of affairs is that we don't have haddocks.

@bjornbm, do you have tools you use to process the markdown to create PDF or HTML documentation from files in this style? I assume such tools are out there, but I'm having trouble figuring out which if any are in active use by the community.

* http://pandoc.org/README.html#literate-haskell-support
* https://github.com/sol/markdown-unlit
* https://ghc.haskell.org/trac/ghc/wiki/LiterateMarkdown (some effort to modify GHC to improve this story, not sure what the status of it is)

I'd lean towards voting for ordinary `.hs` style with haddock documentation. Some of the current explanatory discourse could move to named chunks and appear at the appropriate place in the export lists. Others could sensibly be attached to individual definitions. Still others might (I'm not sure) be better demoted to ordinary comments that aren't visible in the exported documentation.

If we make the other choice, I'd vote for doing it across the board, and for writing haddocks at least for the non-obvious things.

Either way, I'm happy to do the busywork of converting to whatever style is chosen.

**Comment by bjornbm** [comment]
I think we are in agreement on this one. :) See #44.

**Comment by dmcclean** [comment]
Yikes. Ooops.

That's really strange that I missed that, since I had just read through all the open issues looking for ones to close.

Sorry.
