### ISSUE TITLE
Generalize dimensionlessLength

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#52]
Now that `Foldable` is in the prelude, can we generalize `dimensionlessLength :: Num a => [Dimensional v d a] -> Dimensionless a` to `(Foldable f, Num a) => f (Dimensional v d a) -> Dimensionless a`?

**Comment by dmcclean** [comment]
Same comment on `sum`, whose prelude type also got generalized, and on `mean`.

**Comment by bjornbm** [comment]
Yes!

**Comment by dmcclean** [comment]
Will do this after we resolve #44 since it also impacts documentation.
