### ISSUE TITLE
Separate dimensions and dimension arithmetic into its own module

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#53]
Can we separate `Dimension` and `Dimension'` and all the type-level operators on dimensions into their own module? It would result in cleaner documentation, shorten the main module, and could be re-exported by 'Numeric.Units.Dimensional.DK' so that clients wouldn't need to care.

**Comment by bjornbm** [comment]
This sounds reasonable to me, assuming there are no unexpected side effect (have all GHC issues with explicit/implicit exporting of kinds been resolved, if there were any?). Maybe the easiest thing is to try it and see if/how it works!

**Comment by dmcclean** [comment]
Will do this after we resolve #44 since it also impacts documentation.

**Comment by dmcclean** [comment]
Would also like to decide whether #59 is a good idea before doing this, otherwise there is going to be a complicated merge.
