### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#60]
Are there any objections to setting up this repository to use travis-ci?

Because it's open source, it's free, and their server will automatically run the build and tests (once we fix them) after each commit. It also runs it on each PR so that you can see whether merging it will break the build before you decide.

I can set up the configuration, but only the repository owner can actually turn it on. As a result, @bjornbm would need to sign up for an account on travis-ci.org using his github account and grant [certain permissions](http://docs.travis-ci.com/user/github-oauth-scopes/) to their servers.

If we decide to do this you can sign up at any time, but probably shouldn't flip the on switch until we have the configuration file in place.

**Comment by bjornbm** [comment]
Sounds good to me. If you let me know when it is set up I will sign up for the account.

**Comment by dmcclean** [comment]
Travis also can run both the 7.8 and 7.10 builds, which will be nice to prevent mistakes like the one I just made. :)

**Comment by dmcclean** [comment]
Hmm, snag. In practical purposes this is dependent on having `numtype-dk` on hackage. There is probably some way to script it to fetch the `numtype-dk` master branch and do the whole `cabal sandbox add-source` thing, but that is probably more effort than it's worth. :frowning:

I will redirect some effort towards making sure that is release-ready.

**Comment by dmcclean** [comment]
Works preliminarily, for 7.8 only. Now following some instructions from https://github.com/hvr/multi-ghc-travis to get both, since the out-of-the-box configuration doesn't have 7.10 yet and may not for a while

**Comment by dmcclean** [comment]
Works great, 7.8.4 and 7.10.1!

**Comment by bjornbm** [comment]
Signed up at travis-ci and set up the repos to build automagically. Made some inconsequential commits to provoke builds. Ridiculously easy thanks to your legwork! :)

**Comment by dmcclean** [comment]
Nice. It really is a pretty awesome service. I have no idea how they are managing to have it be free for open source, seems like a lot of server resources needed.
