### ISSUE TITLE
Value of mmHg

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#64]
There seems to be some dispute over the value of the millimeter of mercury column.

## master

`prefix 13.5951 (gram * centi meter ^ neg3 * milli meter * gee)`

## UCUM, on their own authority or at least without a footnote

Table 18: Units Used Predominantly in Clinical Medicine meter:

meter of mercury column = 133.3220 kPa
so mmHg = 133.3220 Pa

## NIST Guide

Table 9: Other non-SI units accepted for use with the SI either by the CIPM and this Guide (indicated by*), or by this Guide (indicated by**)

mmHg = 133.322 Pa

## Wikipedia, citing the British Standards Institution

> A millimeter of mercury is a manometric unit of pressure, formerly defined as the extra pressure generated by a column of mercury one millimetre high and now defined as precisely 133.322387415 pascals. [[1](http://en.wikipedia.org/wiki/Millimeter_of_mercury#cite_note-1)]

(seriously? 12 places? :rage:)

## Discussion

I assume we agree that the BSI can pound sand? I'd like to match the UCUM definition so that our parser can be compliant, thankfully they agree with NIST.

**Comment by dmcclean** [comment]
There is a worse situation with the inch of mercury, where UCUM disagrees with Appendix B.8 of the NIST guide. UCUM defines it so that 1 inHg = 1 inch * 1 mmHg / 1 mm. NIST has another slightly different value citing ISO 80000-3.

**Comment by bjornbm** [comment]
Hmm, for mmHg agreed. Couldn't personally care less about inHg but You could define several with a suitable "subscript". E.g. `inHg_NIST` and `inHg_UCUM` (and/or pick one as the canonical `inHg` and document your choice).  Where your parser would parse "inHg" as `inHg_UCUM` for the sake of compliance.

**Comment by dmcclean** [comment]
Yeah, it is a terrible thing to need to care about, but it's still how the US aviation community does things. Also our meteorologists, at least for public consumption, professionally I think they use millibars.
