### ISSUE TITLE
"Circular" units: are they generative the way square/cubic ones are?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#67]
Electricians in the US use a fairly bizarre unit called the [circular mil](http://en.wikipedia.org/wiki/Circular_mil), defined to be the area of a circle one mil in diameter. (A mil, in turn, being 1e-3 inches.)

We have `square` and `cubic`. Logically `circular` could be in the same category, which would be consistent. But I've also never heard of anyone else anywhere on earth using circular anything-besides-mil as a unit.

It's basically pi / 4 times whatever `square` would give you.

**Comment by bjornbm** [comment]
To avoid polluting the namespace I would suggest adding `circularMil` to NonSI. If we later find more "circular" units we could consider adding `circular`. Or would you like a generally applicable `circular`, and if so in which module?





Arguably `square` and `cubic` are also namespace pollution for a fairly narrow use, but at least they are in the NIST guide.

**Comment by dmcclean** [comment]
Agreed, I just thought I would run it by you to make sure we were on the same page.

Plan is to add `circularMil` to `NonSI` on the grounds that while `circular` is generally applicable, nobody ever applies it, and the world would probably be a better place if it stays that way.
