### ISSUE TITLE
Functor

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#68]
In #29 and #19 we discussed whether the `Dimensional` constructor should be exposed, and whether to have a `Functor` instance.

We came down on the side of no, which I strongly agree with, because it breaks the abstraction. We exposed `dmap` from `DK` but not `DK.Prelude` so that people could get at this if they wanted to, but wouldn't get it by default.

I now propose that we add a `Functor` instance, but put it in a separate module.

```haskell
{-# LANGUAGE OverlappingInstances #-}
{-# OPTIONS_GHC -fno-warn-orphan-instances #-}
module Numeric.Units.Dimensional.DK.DubiousFunctorInstance where

import Numeric.Units.Dimensional.DK

instance Functor (Dimensional v d) where
  fmap = dmap
```

The purpose of this is to empower users to make the choice for themselves. One specific reason for making such a choice would be to be able to get along with Edward's linear package.

**Comment by bjornbm** [comment]
OK with me. If you prefer you can call the module .Functor and document the dubiousness.

**Comment by dmcclean** [comment]
Will do.

Also discovered in preparing this patch that 7.10 deprecated 7.8.4's way of specifying overlappingness.
