### ISSUE TITLE
Exact conversion factors

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#70]
Would they be worth taking a dependency on the exact-pi library (which itself only depends on base)?

This question only really applies to the named-units branch, because it requires all the same machinery for making `Unit` a `data` type while keeping `Quantity` as a `newtype`. It arises for the same reason (wanting to add extra runtime information to units).

It's one of the first steps in a long road that leads to useful fixed point quantity types.

**Comment by bjornbm** [comment]
That is fine with me as we know and trust the maintainer of exact-pi. ;)

**Comment by bjornbm** [comment]
I note that exact-pi depends on groups too.

**Comment by dmcclean** [comment]
Sorry, I forgot that. I'm thinking about dropping it because it doesn't really prove much since the rest of the ecosystem doesn't really use groups. (Which seems odd, we have so many typeclasses for every kind of algebraic construction under the sun, but not groups?)

**Comment by dmcclean** [comment]
That's that sorted: http://hackage.haskell.org/package/exact-pi-0.2.0.0

**Comment by dmcclean** [comment]
The statically tracked version of this, which is the one that gets you to the useful fixed point types, is an offense against nature without `PartialTypeSignatures`. The runtime one is still nice, though.

**Comment by dmcclean** [comment]
So the version of this that would get you to useful fixed point values, that are statically tagged with the conversion factor between increments of that fixed point representation and SI units, is possible but it requires changing every type signature for a unit from something like:

```
gee :: Fractional a => Unit 'Metric DAcceleration a
```

to something like:

```
gee :: Fractional a => Unit 'Metric _ DAcceleration a
```

where the partial type signature saves you from needing to write out the type level version of the `ExactPi` value of 196133 / 20000.

An interesting question is whether this is much worse than any of the other extensions we require, but another interesting question is whether it is worth it.

It doesn't pollute the types of quantities (except the new sort of quantities that are fixed point), only units.

**Comment by dmcclean** [comment]
If you are interested and get a chance, take a look at the (unreleased) version of exact-pi that does type-level exact pi values.

It works, but it would be nicer if it had a kind for positive naturals, because the current encoding encodes lots of zeros and lots of divisions by zero. Doing that is a fair amount of hassle though, because you can't just write GHC's built in nats anymore. I also tried the representation where you store numerator-1 and denominator-1 and do all the adding and subtracting in the multiplication type family, but that ends up running afoul of a restriction on nested type family applications and requiring UndecidableInstances. Leaning towards just embracing the chaos.

**Comment by bjornbm** [comment]
You're referring to https://github.com/dmcclean/exact-pi/blob/static/src/Data/ExactPi/TypeLevel.hs? Looks pretty clean to me, I assume you found a way around the problems you were having?

**Comment by dmcclean** [comment]
It is clean, it works, and it does what it is meant to do.

I only meant that it gets that cleanliness by allowing ugly types like `ExactPi' 'True 'Pos3 0 6` = exactly (0/6) * pi^3 (better known as zero) and `ExactPi' 'True 'Zero 6 0` which isn't a number at all. In a perfect world one might wish to catch the second one at compilation time.
