### ISSUE TITLE
Fixity of `*~`, `/~`

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#71]
I'm a little hazy on how GHC's fixity declaration system works.

Is there any way we can make it so we can write:

    1 *~ poundForce / inch ^ pos2

instead of

    1 *~ (poundForce / inch ^ pos2)

Or would it make something horrible happen in some other sort expression?

**Comment by bjornbm** [comment]
Operator fixity is assigned precedence like this (haskell 98):

```haskell
infixr 9  .
infixr 8  ^, ^^, **
infixl 7  *, /, `quot`, `rem`, `div`, `mod`
infixl 6  +, -
infixr 5  :    -- apparently this isn't legal syntax?
infix  4  ==, /=, <, <=, >=, >
infixr 3  &&
infixr 2  ||
infixl 1  >>, >>=
infixr 1  =<<
infixr 0  $, $!, `seq`
```

For dimensional's operators I used the same fixities.

To give `*~` lower precedence than `*` it would have to be `infixl 6`, but then it would be the same as `+` and `-` which isn't what you want. You could perhaps decrease `+` and `-`, but then they won't work as you would expect with `:`. I think it would be a bad idea/unpleasant surprise to have dimensional's operators behave diffent

**Comment by dmcclean** [comment]
I'm slightly confused by this part of the report, https://www.haskell.org/onlinereport/exps.html, specifically the paragraph beginning "Expressions involving infix operators", which I can't reproduce here well because it relies on lots of superscripts to make any sense.

If "Consecutive unparenthesized operators with the same precedence must both be either left or right associative to avoid a syntax error." and `*~` and `*` are both `infixl 7` does that mean that `1 *~ poundForce / (inch ^ pos2)` would be accepted?

I asked the compiler and I got a complaint about mismatched types that doesn't make a heck of a lot of sense.

```
C:\Users\Douglas\Documents\GitHub\dimensional-dk\Numeric\Units\Dimensional\DK\NonSI.hs: line 134, column 64:
  Couldn't match type 'Numeric.Units.Dimensional.DK.Variants.DQuantity
                        Numeric.Units.Dimensional.DK.Variants.* 'Numeric.Units.Dimensional.DK.Variants.DUnit
                                                                  'NonMetric
                   with 'Numeric.Units.Dimensional.DK.Variants.DQuantity
    Expected type: Quantity DPressure a
      Actual type: Dimensional
                     ('Numeric.Units.Dimensional.DK.Variants.DQuantity
                      Numeric.Units.Dimensional.DK.Variants.* 'Numeric.Units.Dimensional.DK.Variants.DUnit
                                                                'NonMetric)
                     (DForce
                      / 'Dim
                          'Numeric.NumType.DK.Integers.Pos2
                          'Numeric.NumType.DK.Integers.Zero
                          'Numeric.NumType.DK.Integers.Zero
                          'Numeric.NumType.DK.Integers.Zero
                          'Numeric.NumType.DK.Integers.Zero
                          'Numeric.NumType.DK.Integers.Zero
                          'Numeric.NumType.DK.Integers.Zero)
                     a
```

These types are the same if you apply the type family definitions, AFAICS. And I'm not sure why changing the grouping should change this.

This one also works: `1 *~ (poundForce / (inch ^ pos2))`.

**Comment by bjornbm** [comment]
I'm having difficulties parsing that error message myself. But:

    1 *~ poundForce / (inch ^ pos2)

will be interpreted as:

    (1 *~ poundForce) / (inch ^ pos2)

which is a error since we don't allow dividing a quantity by a unit (except with `/~`).

Another thing to note is that you got a type checker error, while the note in the report is regarding syntax error. The expression in question is not a syntax error and is “accepted” by the syntax checker.

**Comment by dmcclean** [comment]
Ahh, OK, got it. So the essential problem is that there's no such thing as `infixl 6.5`.

So I'm closing this as impossible. It would be nice but it isn't worth breaking the things we would need to break.
