### ISSUE TITLE
Num vs Fractional context for the SI coherent derived units

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#77]
We have, choosing one example arbitrarily:
```haskell
pascal :: Fractional a => Unit DPressure a
pascal = newton / meter ^ pos2
```

But we could have:
```haskell
pascal :: Num a => Unit DPressure a
pascal = siUnit
```

because we know that, as a coherent unit, it's value is `1`. The cost is a less self-explanatory definition, which could be addressed by comments?

(This question arises more acutely in the branch that tracks exact conversion factors, but even without that feature it is an interesting question IMO.)

**Comment by bjornbm** [comment]
The other benefit is that `newton / meter ^ pos2` actually makes sure that
`DPressure` is correctly defined, which I think it is a nice check to have.
It could perhaps move to a test suite but that would be more cumbersome.

That being said, I may be willing to reconsider depending on the benefits
in your branch.

**Comment by dmcclean** [comment]
That is a solid objection, because it is an important thing to check.

If we do decide to move it to a test suite, it would involve replacing this comment here https://github.com/bjornbm/dimensional-dk/blob/master/tests/Numeric/Units/Dimensional/DK/QuantitiesTest.hs#L33-L34 with more lines like the ones above/below it.

I am going to change my branch to be this way. I initially went through enough hoops to keep it the way it is, but it involves a higher-rank type and some function/function' pairs and a whole lot of complexity that ultimately isn't worth it. I will add the corresponding test cases.

**Comment by dmcclean** [comment]
Clarification: The more lenient context is unobjectionable in itself, right?

**Comment by bjornbm** [comment]
Right.

**Comment by dmcclean** [comment]
I am ending up relying on the tests/changing these definitions to just reference `siUnit` in the named units branch. I had an implementation that didn't need to, but it wasn't as safe and it had to expose confusingly similar unit construction functions.
